[project]
name = "pytest-tzheader"
version = "0.1.0"
description = "Show the time zone in pytest's header."
requires-python = ">=3.10"
dependencies = ["pytest>=8.4"]

[project.entry-points.pytest11]
tzheader = "pytest_tzheader.plugin"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.pytest.ini_options]
testpaths = ["tests"]
addopts = ["-p", "pytester"]
