{{- if .Values.ingress.enabled }}
{{- if not .Values.service.enabled }}
{{- fail "ingress.enabled needs service.enabled" }}
{{- end }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "app.fullname" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.ingress.className }}
  ingressClassName: {{ . }}
  {{- end }}
  {{- with .Values.ingress.tlsSecretName }}
  tls:
    - hosts: [{{ required "ingress.host is required with TLS" $.Values.ingress.host | quote }}]
      secretName: {{ . }}
  {{- end }}
  rules:
    - {{- with .Values.ingress.host }}
      host: {{ . | quote }}
      {{- end }}
      http:
        paths:
          - path: {{ .Values.ingress.path }}
            pathType: Prefix
            backend:
              service:
                name: {{ include "app.fullname" . }}
                port:
                  name: http
{{- end }}
